name: frontend
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  get_it: ^7.2.0
  badges: ^2.0.2
  flutter_dotenv: ^5.0.2
  flutter_sound_lite: ^8.5.0
  permission_handler: ^9.1.0
  path_provider: ^2.0.9
  flutter_tts: ^3.3.3
  dio: ^4.0.4
  google_fonts: ^2.3.1
  camera: ^0.9.4+14
  image_picker: ^0.8.4+10
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.5
  speech_to_text: ^5.4.3
  avatar_glow: ^2.0.2

flutter_native_splash:
  background_image: assets/images/opening_background.png
  image: assets/images/opening_logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/nihogalog_logo.png
    - .env.production
    - .env.development

  fonts:
    - family:  DrawerIcons
      fonts:
        - asset: assets/icons/DrawerIcons.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
   
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
